twig:
    file_name_pattern: '*.twig'
    #form_themes: ['bootstrap_5_layout.html.twig']
    form_themes: ['form/bootstrap_5/layout.html.twig'] #ajout de notre template personalise

when@test:
    twig:
        strict_variables: true
