controllers:
    prefix: "{_locale}"
    requirements:
        _locale: en|fr|de|ru
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#home:
#    path: /
#    controller: App\Controller\HomeController::index